# Generated by Django 4.1.3 on 2023-01-25 15:15

import cloudinary.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_backend', '0002_alter_hotel_rating_alter_order_date_ordered'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='image',
            field=cloudinary.models.CloudinaryField(default=1, max_length=255, verbose_name='image'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='date_ordered',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 25, 17, 15, 34, 817664)),
        ),
    ]
