# Generated by Django 4.1.3 on 2023-01-25 15:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_backend', '0004_alter_order_date_ordered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_ordered',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 25, 17, 34, 27, 611225)),
        ),
        migrations.AlterField(
            model_name='room',
            name='is_available',
            field=models.BooleanField(blank=True, default=1, null=True),
        ),
    ]
