# Generated by Django 4.1.3 on 2023-01-25 16:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_backend', '0005_alter_order_date_ordered_alter_room_is_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_ordered',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 25, 18, 1, 19, 221582)),
        ),
        migrations.AlterField(
            model_name='room',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
